feat: dev to test (#477)
* feat(EWM-264): account balances (#474)

Co-authored-by: Egor Komarov <egor.komarov@bf.rocks>

* refactor: Remove language menu (#476)

* app-deploy.yaml on push branches test

* Add branch-workflow.yaml

* melos.yaml add deploy_ios, deploy_android, deploy_fad commands

* Update README.md

* Rename to deploy_fad_ios and deploy_fad_android

* Move get SENTRY_DSN to build.sh

* build.sh deploy to store only from main

* app-deploy.yaml store job check branch to deploy to stores

* Hide language item from menu in profile

* Update build flow

* Update Readme Deploy from local machine section

* Fix android-deploy orders

* fix: Ewm 250 (#478)

* EWM-250. Fix add seed

* PopScope replace onPopInvoked -> onPopInvokedWithResult + addPostFrameCallback

* Remove todo

* add check didPop in onPopInvokedWithResult

* Fix create new seed from profile

* Fix analyzer issue

* SeedPhraseModel

---------

Co-authored-by: Egor Komarov <Odrin@users.noreply.github.com>
Co-authored-by: Egor Komarov <egor.komarov@bf.rocks>

diff --git a/.github/workflows/app-deploy.yaml b/.github/workflows/app-deploy.yaml
--- a/.github/workflows/app-deploy.yaml
+++ b/.github/workflows/app-deploy.yaml
@@ -3,7 +3,7 @@ name: Deploy app
 on:
   push:
     branches:
-      - main
+      - test
   workflow_dispatch:
     inputs:
       deploy_target:
@@ -33,6 +33,16 @@ jobs:
       - uses: actions/checkout@v4
         with:
           fetch-depth: 1
+
+      - name: Check deploy target and branch
+        run: |
+          if [[ "${{ github.ref }}" != "refs/heads/main" && 
+                ( "${{ inputs.deploy_target }}" == "store" || 
+                  "${{ inputs.deploy_target }}" == "ios_store" || 
+                  "${{ inputs.deploy_target }}" == "android_store" ) ]]; then
+            echo "🚫 Error: Deployment to store, ios_store, or android_store is only allowed from the 'main' branch."
+            exit 1
+          fi
 
       - name: Set output for flutter_version
         id: set_output
@@ -133,25 +143,16 @@ jobs:
       - name: Generate dart code
         run: melos codegen --no-select
 
-      # Read Sentry DSN
-      - name: Read Sentry DSN
-        id: read_sentry_dsn
-        run: |
-          if [ -f ./secrets/sentry-dsn.txt ]; then
-            SENTRY_DSN=$(cat ./secrets/sentry-dsn.txt)
-            echo "SENTRY_DSN=$SENTRY_DSN" >> $GITHUB_ENV
-            echo "::add-mask::$SENTRY_DSN"
-          fi
-
       - name: Display Build Number
         run:
           echo "Number is = ${{ needs.setup.outputs.build_number }}"
 
       - name: Build and deploy
         run: |
-          bash scripts/build.sh ${{ env.ios_target }} ${{ needs.setup.outputs.build_number }}
-        env:
-          SENTRY_DSN: ${{ env.SENTRY_DSN }}
+          bash scripts/build.sh \
+          --deploy-target ${{ env.ios_target }} \
+          --build-number ${{ needs.setup.outputs.build_number }} \
+          --upload true
 
       - name: Clean Xcode Derived Data
         run: |
@@ -175,17 +176,17 @@ jobs:
   # Android deploy
   android-deploy:
     needs: setup
+    runs-on: ubuntu-latest
 
     if: ${{ inputs.deploy_target == 'fad' || inputs.deploy_target == 'store' || inputs.deploy_target == 'android_fad' || inputs.deploy_target == 'android_store' }}
 
-    runs-on: ubuntu-latest
     env:
       SECRET_PASSPHRASE: ${{ secrets.SECRET_PASSPHRASE }}
       MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
 
     steps:
       - name: Reinstall existing fastlane plugin
-        run: | 
+        run: |
           sudo gem uninstall fastlane-plugin-firebase_app_distribution
           gem install fastlane-plugin-firebase_app_distribution --user-install
 
@@ -231,25 +232,16 @@ jobs:
       - name: Generate dart code
         run: melos codegen --no-select
 
-      # Read Sentry DSN
-      - name: Read Sentry DSN
-        id: read_sentry_dsn
-        run: |
-          if [ -f ./secrets/sentry-dsn.txt ]; then
-            SENTRY_DSN=$(cat ./secrets/sentry-dsn.txt)
-            echo "SENTRY_DSN=$SENTRY_DSN" >> $GITHUB_ENV
-            echo "::add-mask::$SENTRY_DSN"
-          fi
-
       - name: Display Build Number
         run:
           echo "Number is = ${{ needs.setup.outputs.build_number }}"
 
       - name: Build and deploy
         run: |
-          bash scripts/build.sh ${{ env.android_target }} ${{ needs.setup.outputs.build_number }}
-        env:
-          SENTRY_DSN: ${{ env.SENTRY_DSN }}
+          bash scripts/build.sh \
+          --deploy-target ${{ env.android_target }} \
+          --build-number ${{ needs.setup.outputs.build_number }} \
+          --upload true
 
       - name: Remove Flutter
         run: |
