chore: Update CI (#472)
* Remove unused import

* Format code

* version: 1.0.0+1

* analysis_options.yaml exclude main.reflectable.dart

* version: 1.0.1

* setup-ndk

* setup-ndk if != store_ios

* ndk-version: r23c

* Clear Gradle Cache and temp files

* android/build.gradle add buildscript section

* Update app-deploy.yaml

* Single build.sh instead multiple

* Separate workflows

* Get build number in parent workflow

* Remove contains() from if in workflow

* Remove . from path to workflow deploy folder

* Move child workflows to level with app-deploy.yaml

* Combined adnroid and ios workflows into one

* Deploy app

* Variable of flutter-version in setup job

* Add check $BUILD_NUMBER in setup job

* env FLUTTER_VERSION

* Install Dart dependencies

* setup job Decrypt secrets

* setup job melos

* setup job env SECRET_PASSPHRASE and MATCH_PASSWORD

* Fix check BUILD_NUMBER

* Fix Get build number

* get-build-number.sh echo only number

* get-build-number.sh single echo

* flutter_version GITHUB_ENV -> GITHUB_OUTPUT

* needs.setup.outputs.build_number

* Display Build Number

* build_number GITHUB_OUTPUT

* export BUILD_NUMBER_STRING

* Mapping deploy_target to target

* fi

* ios_target and android_target

* echo "Error: Build number is not specified."

* deploy_target if [[]]

* android-deploy install ndk after java

* Android after ios job and Remove flutter

* Mask sensitive data

* Mask SENTRY_DSN

* Remove check job success

* Mask SENTRY_DSN on Read Sentry DSN step

* android-deploy:
    needs: setup

* android-deploy job use ubuntu-latest

* fix browser_resource_item import

* browser_start_view.dart fix browser_resource_item import

* remove separate install ndk

* Reinstall existing fastlane plugin

* Update get_build_number_test.dart

diff --git a/.github/workflows/app-deploy.yaml b/.github/workflows/app-deploy.yaml
--- a/.github/workflows/app-deploy.yaml
+++ b/.github/workflows/app-deploy.yaml
@@ -1,10 +1,9 @@
-name: Deploy main app
+name: Deploy app
 
 on:
   push:
     branches:
       - main
-  # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
     inputs:
       deploy_target:
@@ -15,34 +14,112 @@ on:
         options:
           - "fad"
           - "store"
-          - "fad_store"
+          - "ios_fad"
           - "ios_store"
+          - "android_fad"
           - "android_store"
 
 jobs:
-  build_and_deploy:
+  setup:
+    runs-on: ubuntu-latest
+    outputs:
+      build_number: ${{ steps.get_build_number.outputs.build_number }}
+      flutter_version: ${{ steps.set_output.outputs.flutter_version }}
+    env:
+      SECRET_PASSPHRASE: ${{ secrets.SECRET_PASSPHRASE }}
+      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
+      FLUTTER_VERSION: '3.24.0'
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          fetch-depth: 1
+
+      - name: Set output for flutter_version
+        id: set_output
+        run: |
+          echo "flutter_version=${FLUTTER_VERSION}" >> $GITHUB_OUTPUT
+
+      - name: Setup Flutter
+        uses: subosito/flutter-action@v2
+        with:
+          flutter-version: ${{ env.FLUTTER_VERSION }}
+          channel: 'stable'
+          cache: true
+          cache-key: flutter-:os:-:channel:-:version:-:arch:-:hash:-${{ hashFiles('**/pubspec.lock') }}
+
+      - name: Install Dart dependencies
+        run: dart pub get
+
+      - uses: bluefireteam/melos-action@v3
+
+      # Secrets
+      - name: Decrypt secrets
+        run: melos decrypt-secrets
+
+      - name: Get build number
+        id: get_build_number
+        run: |
+          BUILD_NUMBER=$(bash scripts/get-build-number.sh)
+          if [ -z "$BUILD_NUMBER" ]; then
+            echo "Error: Build number is not specified."
+            exit 1
+          fi
+          echo "#️⃣ New build number: $BUILD_NUMBER"
+          echo "build_number=$BUILD_NUMBER" >> $GITHUB_OUTPUT
+
+      - name: Check Flutter Path
+        run: echo "Flutter path is = $FLUTTER_ROOT"
+
+      - name: Remove Flutter
+        run: |
+          rm -rf $FLUTTER_ROOT
+          echo "Flutter removed to free up space"
+
+      - name: Clean Dart dependencies
+        run: |
+          rm -rf .dart_tool/
+          rm -rf $HOME/.pub-cache/
+
+  # iOS deploy
+  ios-deploy:
+    needs: setup
     runs-on: macos-latest
+
+    if: ${{ inputs.deploy_target == 'fad' || inputs.deploy_target == 'store' || inputs.deploy_target == 'ios_fad' || inputs.deploy_target == 'ios_store' }}
+
     env:
       SECRET_PASSPHRASE: ${{ secrets.SECRET_PASSPHRASE }}
       MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
 
     steps:
-      # Setup
       - uses: actions/checkout@v4
         with:
-          fetch-depth: 50
-      - uses: subosito/flutter-action@v2
+          fetch-depth: 1
+
+      - name: Set target variable based on deploy_target
+        run: |
+          echo "deploy_target is = ${{ inputs.deploy_target }}"
+          if [[ "${{ inputs.deploy_target }}" == "fad" || "${{ inputs.deploy_target }}" = "ios_fad" ]]; then
+            echo "ios_target=ios_fad" >> $GITHUB_ENV
+          elif [[ "${{ inputs.deploy_target }}" == "store" || "${{ inputs.deploy_target }}" ==  "ios_store" ]]; then
+            echo "ios_target=ios_store" >> $GITHUB_ENV
+          fi
+
+      - name: Display ios_target value
+        run: echo "ios_target is set to = ${{ env.ios_target }}"
+
+      - name: Setup Flutter
+        uses: subosito/flutter-action@v2
         with:
-          flutter-version: '3.24.0'
+          flutter-version: ${{ needs.setup.outputs.flutter_version }}
           channel: 'stable'
           cache: true
           cache-key: flutter-:os:-:channel:-:version:-:arch:-:hash:-${{ hashFiles('**/pubspec.lock') }}
+
+      - name: Display Flutter version
+        run: flutter --version
+
       - uses: bluefireteam/melos-action@v3
-      - uses: actions/setup-java@v4
-        if: inputs.deploy_target != 'store_ios'
-        with:
-          distribution: zulu
-          java-version: "17.x"
 
       # Secrets
       - name: Decrypt secrets
@@ -50,7 +127,6 @@ jobs:
 
       # iOS certs
       - name: Making sure the iOS certificates and profiles are installed
-        if: inputs.deploy_target != 'store_android'
         run: melos build:ios_match_assure
 
       # Dart/Flutter
@@ -64,39 +140,123 @@ jobs:
           if [ -f ./secrets/sentry-dsn.txt ]; then
             SENTRY_DSN=$(cat ./secrets/sentry-dsn.txt)
             echo "SENTRY_DSN=$SENTRY_DSN" >> $GITHUB_ENV
+            echo "::add-mask::$SENTRY_DSN"
           fi
 
-      # Build and deploy to FAD
-      - name: Build and deploy to FAD
-        if: inputs.deploy_target == 'fad'
-        run: melos build:deploy_fad
+      - name: Display Build Number
+        run:
+          echo "Number is = ${{ needs.setup.outputs.build_number }}"
+
+      - name: Build and deploy
+        run: |
+          bash scripts/build.sh ${{ env.ios_target }} ${{ needs.setup.outputs.build_number }}
         env:
           SENTRY_DSN: ${{ env.SENTRY_DSN }}
 
-      # Build and deploy to STORE
-      - name: Build and deploy to STORE
-        if: inputs.deploy_target == 'store'
-        run: melos build:deploy_store
+      - name: Clean Xcode Derived Data
+        run: |
+          rm -rf ~/Library/Developer/Xcode/DerivedData
+
+      - name: Clean CocoaPods cache
+        run: |
+          pod cache clean --all
+          rm -rf ios/Pods
+          rm -rf ios/Podfile.lock
+
+      - name: Remove Flutter
+        run: |
+          rm -rf $FLUTTER_ROOT
+
+      - name: Clean Dart dependencies
+        run: |
+          rm -rf .dart_tool/
+          rm -rf $HOME/.pub-cache/
+
+  # Android deploy
+  android-deploy:
+    needs: setup
+
+    if: ${{ inputs.deploy_target == 'fad' || inputs.deploy_target == 'store' || inputs.deploy_target == 'android_fad' || inputs.deploy_target == 'android_store' }}
+
+    runs-on: ubuntu-latest
+    env:
+      SECRET_PASSPHRASE: ${{ secrets.SECRET_PASSPHRASE }}
+      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
+
+    steps:
+      - name: Reinstall existing fastlane plugin
+        run: | 
+          sudo gem uninstall fastlane-plugin-firebase_app_distribution
+          gem install fastlane-plugin-firebase_app_distribution --user-install
+
+      - uses: actions/checkout@v4
+        with:
+          fetch-depth: 1
+
+      - name: Set target variable based on deploy_target
+        run: |
+          echo "deploy_target is = ${{ inputs.deploy_target }}"
+          if [[ "${{ inputs.deploy_target }}" == "fad" || "${{ inputs.deploy_target }}" = "android_fad" ]]; then
+            echo "android_target=android_fad" >> $GITHUB_ENV
+          elif [[ "${{ inputs.deploy_target }}" == "store" || "${{ inputs.deploy_target }}" ==  "android_store" ]]; then
+            echo "android_target=android_store" >> $GITHUB_ENV
+          fi
+
+      - name: Display android_target value
+        run: echo "android_target is set to = ${{ env.android_target }}"
+
+      - name: Setup Flutter
+        uses: subosito/flutter-action@v2
+        with:
+          flutter-version: ${{ needs.setup.outputs.flutter_version }}
+          channel: 'stable'
+          cache: true
+          cache-key: flutter-:os:-:channel:-:version:-:arch:-:hash:-${{ hashFiles('**/pubspec.lock') }}
+
+      - name: Display Flutter version
+        run: flutter --version
+
+      - uses: bluefireteam/melos-action@v3
+
+      - uses: actions/setup-java@v4
+        with:
+          distribution: zulu
+          java-version: "17.x"
+
+      # Secrets
+      - name: Decrypt secrets
+        run: melos decrypt-secrets
+
+      # Dart/Flutter
+      - name: Generate dart code
+        run: melos codegen --no-select
+
+      # Read Sentry DSN
+      - name: Read Sentry DSN
+        id: read_sentry_dsn
+        run: |
+          if [ -f ./secrets/sentry-dsn.txt ]; then
+            SENTRY_DSN=$(cat ./secrets/sentry-dsn.txt)
+            echo "SENTRY_DSN=$SENTRY_DSN" >> $GITHUB_ENV
+            echo "::add-mask::$SENTRY_DSN"
+          fi
+
+      - name: Display Build Number
+        run:
+          echo "Number is = ${{ needs.setup.outputs.build_number }}"
+
+      - name: Build and deploy
+        run: |
+          bash scripts/build.sh ${{ env.android_target }} ${{ needs.setup.outputs.build_number }}
         env:
           SENTRY_DSN: ${{ env.SENTRY_DSN }}
 
-      # Build and deploy to FAD and STORE
-      - name: Build and deploy to FAD and STORE
-        if: inputs.deploy_target == 'fad_store'
-        run: melos build:deploy_fad_store
-        env:
-          SENTRY_DSN: ${{ env.SENTRY_DSN }}
+      - name: Remove Flutter
+        run: |
+          rm -rf $FLUTTER_ROOT
+          echo "Flutter removed to free up space"
 
-      # Build and deploy to Test Flight
-      - name: Build and deploy to Test Flight
-        if: inputs.deploy_target == 'ios_store'
-        run: melos build:deploy_ios_store
-        env:
-          SENTRY_DSN: ${{ env.SENTRY_DSN }}
-
-      # Build and deploy to Google Play
-      - name: Build and deploy to Google Play
-        if: inputs.deploy_target == 'android_store'
-        run: melos build:deploy_android_store
-        env:
-          SENTRY_DSN: ${{ env.SENTRY_DSN }}
+      - name: Clean Dart dependencies
+        run: |
+          rm -rf .dart_tool/
+          rm -rf $HOME/.pub-cache/
